# C++ 11/14 support
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\promise2

before_build:
  - cd c:\projects\promise2\test
  - cmake -G "Visual Studio 14 2015 Win64"

build:
  - dir .
  project: promise_test.sln

test_script:
  - ps: Get-ChildItem -Recurse -Filter *.exe | ForEach { Start-Process $_.Fullname }