#ifndef PROMISE_CONFIG_H
#define PROMISE_CONFIG_H

#ifndef DEFERRED_PROMISE
# define DEFERRED_PROMISE 1
#endif // DEFERRED_PROMISE

#ifndef NESTING_PROMISE
# define NESTING_PROMISE 0
#endif // NESTING_PROMISE

#endif // PROMISE_CONFIG_H
